openapi: 3.0.3
info:
  title: Exo 5 TD OAS
  version: 1.0.0
components:
  schemas:
    Product:
      properties:
        name:
          type: string
        expiration_date:
          type: string
          format: date
        price:
          type: number
          format: float
    Order:
      properties:
        identifier:
          type: integer
        customer_name:
          type: string
        creation_datetime:
          type: string
          format: date
        total_amount:
          type: number
          format: float

  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  parameters:
    limitParam:
      name: limit
      in: query
      schema:
        type: integer
      required: false
    queryParam:
      name: q
      in: query
      schema:
        type: string
      required: false
    pageParam:
      name: page
      in: query
      schema:
        type: integer
        example: 1
      required: false
    sizeParam:
      name: size
      in: query
      schema:
        type: integer
        example: 20
      required: false

paths:
  /products:
    get:
      tags:
        - Products
      parameters:
        - $ref: "#/components/parameters/limitParam"
        - $ref: "#/components/parameters/queryParam"
      responses:
        "200":
          description: Retourner une liste de Product
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"

              examples:
                empty:
                  value: []
                exists:
                  value:
                    - name: Potatoes
                      expiration_date: 2025-09-12T14:30:20Z
                      price: 30.5
                    - name: Tomatoes
                      expiration_date: 2025-09-12T14:32:20Z
                      price: 10.25

  /orders:
    get:
      tags:
        - Orders
      parameters:
        - $ref: "#/components/parameters/pageParam"
        - $ref: "#/components/parameters/sizeParam"
      responses:
        "200":
          description: Liste paginée des commandes
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
              example:
                {
                  identifier: 1,
                  customer_name: Jean,
                  creation_datetime: 2020-10-02T10:11:11,
                  total_amount: 100.32,
                }

    post:
      tags:
        - Orders
      security:
        - basicAuth: []
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/Order"
            example:
              {
                identifier: 1,
                customer_name: Jean,
                creation_datetime: 2020-10-02T10:11:11,
                total_amount: 100.32,
              }
      responses:
        "200":
          description: Ajout d'une commande
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
              example:
                {
                  identifier: 1,
                  customer_name: Jean,
                  creation_datetime: 2020-10-02T10:11:11,
                  total_amount: 100.32,
                }
